### PR TITLE
feat: add is valid and revoke methods

### PR DESCRIPTION
**Pull request by NansPellicari**
Hi! For my projects I had to add some features on your component (and thanks for it btw, it is really helpful to me). If you think it is usefull to you I'm glad to share!

### CODE REVIEW

**Comment by NansPellicari** [comment]
Oh sorry! I mess something in the build... I'm on it

**Comment by NansPellicari** [comment]
Ok the problem was due to a **missing polyfill** for `Object.assign()` on the test env.  
'Cause of that, `mount()` function of `vue-test-utils` package didn't works.  

Still a problem occures which break some test codes I try to write :   
Probably due to a version compatibilty (I'm sorry but I am not sure, I spend hours on it but I am mostly a beginner on JS env, maybe you have a clue?), the mock creates by `mount()` does not listen events triggered during the component `mounted`.

So if you don't mind, for now I quote the tests I'm talking about (I can remove them for the sake of clarity), and if you are interested in, I can create a **new pull request** trying to update all dependencies and the test env? Do you mind if I changed with the recommended test-runner [jest](https://vue-test-utils.vuejs.org/guides/choosing-a-test-runner.html)?

**Comment by apertureless** [comment]
Hi @NansPellicari 

thanks for the PR. 
Well, yeah the dev dependencies could be quite outdated. 

I can look the coming days into the error. 

If you want, feel free to swap karma out for jest. I am also mostly using jest now, but back then when the package was created jest wasn't a thing xD

**Review by apertureless — APPROVED** [review]

**Comment by apertureless** [comment]
Hey @NansPellicari !
Can you please update your PR ? I've merged the new jest test env. But now we have some merge conflicts.

**Comment by NansPellicari** [comment]
Sure, of course ! I'm on It

**Comment by NansPellicari** [comment]
Done!

**Pull request merged**
